### ISSUE TITLE
[BUG] Setting a tile to "Trigger using image instead of border" crashes scene upon reload

### ISSUE THREAD

**Issue by Vaialyss** [ironmonk108/monks-active-tiles#555]
**Description**
When attempting to make an interactive overworld map, I used active tile triggers to create city district borders which would only appear on hover-in and would disappear on hover-out, and I used PNG images for the borderlines to allow the hover-in to only trigger when the actual border was contacted, as opposed to the tile perimeter. 
While the function worked like a charm, if I ever exited the world file or even switched to another scene in my world, the scene with the interactive map would cease to exist upon re-entry, instead giving a, "Canvas drawing failed: Cannot read properties of undefined (reading 'x')" error specifically when I had both "Trigger using image instead of border," selected and when I had at least one image applied to the "Images" section of the "Triggers" tab for the tile.

**Steps to reproduce the behavior:**
1. In any scene, create a tile and add one image to the "Images" section of the "Triggers" tab. (I used PNGs. Untested if the issue persists with other image formats.)
2. Under the "Setup" section of the "Triggers" tab for the tile, select, "Trigger using image instead of border."
4. create a second scene and change your current display to the second scene. (It does not matter which scene is activated.)
5. Return to the original scene. The aforementioned error should display at the top of the screen and any images previously present in the original scene should be gone.

**Expected behavior**
The intended interaction is for the original scene to display correctly with the triggering tile still intact and functioning.

**Screenshots**
https://media.discordapp.net/attachments/1029152002363625495/1127872170400419900/Screenshot_56.png?width=996&height=559

**Additional Information**
 - Browser: Google Chrome, though the issue was created within the Foundry VTT application. I have not tested the issue in any browsers.
 - Foundry Version: 10.291
 - Systems: Custom System Builder, DnD 5e
 - Module version: 10.7
 - Console Errors: 
> TypeError: Cannot read properties of undefined (reading 'x')
[Detected 1 package: monks-active-tiles]
    at Tile._findTextureBorder (monks-active-tiles.js:3092:57)
    at monks-active-tiles.js:1472:26
    at async Promise.all (index 0)
    at async TilesLayer._draw (foundry.js:30830:5)
    at async TilesLayer.draw (foundry.js:30349:5)
    at async InterfaceCanvasGroup.draw (foundry.js:26151:9)
    at async InterfaceCanvasGroup.draw (foundry.js:39270:5)
    at async Canvas.draw (foundry.js:23673:11)
    at async Scene.view (foundry.js:20901:7)
onError @ foundry.js:747
foundry.js:59187 Canvas drawing failed: Cannot read properties of undefined (reading 'x')
fetch @ foundry.js:59187
foundry.js:30889 Uncaught (in promise) TypeError: Cannot set properties of null (setting 'visible')
[No packages detected]
    at WallsLayer._deactivate (foundry.js:30889:26)
    at WallsLayer._deactivate (foundry.js:37511:11)
    at WallsLayer.deactivate (foundry.js:30474:10)
    at TilesLayer.activate (foundry.js:30438:76)
    at #initializeCanvasLayer (foundry.js:23846:11)
    at #initialize (foundry.js:23796:32)
    at Canvas.draw (foundry.js:23689:29)
    at async Scene.view (foundry.js:20901:7)

 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: yes. Even with Monk's Active Tiles being the only active mod, the bug still persists.

**Additional context**
Anecdotally, I've so far managed to reproduce the bug consistently around 8-10 times out of the same number of attempts. Often, the bug will take whatever scene's background image got deleted and superimpose that image onto whatever other scenes I load. This happened often, but not every single time I reproduced the issue.

**Comment by ironmonk88** [comment]
Active Tiles 10.7 isn't really supported any more.
Please update to the latest code and check to see if this is still an issue.

**Comment by Vaialyss** [comment]
my apologies. I somehow didn't even realize I was using an outdated version. Thank you for the heads up! Updated to 10.21 and the issue appears to be resolved! 

Anecdotally, I did notice when testing for v10.21 that the option to have an image trigger at the image border instead of the tile border isn't working properly anymore. Now it will frequently trigger tiles I've set to have unique PNG borders when I'm hitting where the tile's perimeter is. I can submit another ticket for this if you'd like.

**Comment by ironmonk108** [comment]
Closing this as the ticket is stale.  And there was a resolution.
